[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://hyurmojmeqzmrmahlqcy.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dXJtb2ptZXF6bXJtYWhscWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODI1MzEsImV4cCI6MjA2NTQ1ODUzMX0.L4567_nwGWLNK08b6rfzVVsaX1AZ1rOHSxOz9j4n1b8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200